// app/events/eventData.ts

export const rawEventData = {
  music: [
    {
      id: 1,
      format: "BANDS ( EASTERN )",
      title: "EASTERN UNBOUND",
      open_to_all: false,
      date: "20.02.2026",
      reporting_time: "8.30 AM",
      venue: "Dr. TP GANESAN AUDITORIUM",
      mode: "Offline",
      participation_type: "TEAM",
      team_size: "8 to 10 members",
    },
    {
      id: 2,
      format: "BANDS ( WESTERN ) ",
      title: "WESTERN UNBOUND",
      open_to_all: false,
      date: "21.02.2026",
      reporting_time: "8.30 AM",
      venue: "VENDHAR SQUARE",
      mode: "Offline",
      participation_type: "TEAM",
      team_size: "8 to 10 members",
    },
    {
      id: 3,
      format: "RAP",
      title: "VERSE CLASH",
      open_to_all: true,
      date: "21.02.2026",
      reporting_time: "2.30 PM",
      venue: "VENDHAR SQUARE",
      mode: "Offline",
      participation_type: "SOLO",
      team_size: "1",
    },
    {
      id: 4,
      format: "BEATBOX",
      title: "RHYTHM RUMBLE",
      open_to_all: true,
      date: "21.02.2026",
      reporting_time: "2.30 PM",
      venue: "VENDHAR SQUARE",
      mode: "Offline",
      participation_type: "SOLO",
      team_size: "1",
    },
    {
      id: 5,
      format: "INSTRUMENTAL",
      title: "CRESCENDO",
      open_to_all: false,
      date: "20.02.2026",
      reporting_time: "1.30 PM",
      venue: "Dr. TP GANESAN  AUDITORIUM - MINI HALL 1",
      mode: "Offline",
      participation_type: "SOLO",
      team_size: "1",
    },
    {
      id: 6,
      format: "WESTERN VOCAL",
      title: "ECHOVERSE",
      open_to_all: true,
      date: "21.02.2026",
      reporting_time: "1.30 PM",
      venue: "BIOTECH BLOCK - PROF. G. N. RAMACHANDRAN HALL",
      mode: "Offline",
      participation_type: "SOLO",
      team_size: "1",
    },
    {
      id: 7,
      format: "EASTERN CLASSICAL VOCAL",
      title: "SWARANJALI",
      open_to_all: false,
      date: "20.02.2026",
      reporting_time: "1.30 PM",
      venue: "BIOTECH BLOCK - PROF. G. N. RAMACHANDRAN HALL",
      mode: "Offline",
      participation_type: "SOLO",
      team_size: "1",
    },
  ],

  dance: [
    {
      id: 8,
      format: "CLASSICAL",
      title: "RASADHARA",
      open_to_all: true,
      date: "21.02.2026",
      reporting_time: "8.30 AM",
      venue: "Dr. TP GANESAN AUDITORIUM - MINI HALL 1",
      mode: "Offline",
      participation_type: "SOLO",
      team_size: "1",
    },
    {
      id: 9,
      format: "CREATIVE CHOREOGRAPHY",
      title: "NRITYA NATYA",
      open_to_all: false,
      date: "20.02.2026",
      reporting_time: "1.30 PM",
      venue: "Dr. TP GANESAN AUDITORIUM",
      mode: "Offline",
      participation_type: "TEAM",
      team_size: "8 to 20 performers",
    },
    {
      id: 10,
      format: "WESTERN",
      title: "METROPOLIS MOVES",
      open_to_all: false,
      date: "20.02.2026",
      reporting_time: "8.30 AM",
      venue: "Dr. TP GANESAN AUDITORIUM - MINI HALL 1",
      mode: "Offline",
      participation_type: "SOLO",
      team_size: "1",
    },
    {
      id: 11,
      format: "1 vs 1 BATTLE",
      title: "URBAN SHOWDOWN",
      open_to_all: true,
      date: "20.02.2026",
      reporting_time: "1.30 PM",
      venue: "VENDHAR SQUARE",
      mode: "Offline",
      participation_type: "SOLO",
      team_size: "1",
    },
    {
      id: 12,
      format: "GROUP DANCE",
      title: "CHOREONITE",
      open_to_all: false,
      date: "21.02.2026",
      reporting_time: "1.30 PM",
      venue: "Dr. TP GANESAN AUDITORIUM",
      mode: "Offline",
      participation_type: "TEAM",
      team_size: "8 to 25 performers",
    },
    {
      id: 13,
      format: "TRADITIONAL FOLK",
      title: "VIRSA",
      open_to_all: false,
      date: "22.02.2026",
      reporting_time: "8.30 AM",
      venue: "VENDHAR SQUARE",
      mode: "Offline",
      participation_type: "TEAM",
      team_size: "8 to 20 performers",
    },
  ],

  fashion: [
    {
      id: 14,
      format: "DUO EVENT",
      title: "AU-DELÀ:Mr. & MISS MILAN",
      open_to_all: true,
      date: "22.02.2026",
      reporting_time: "1.30 PM",
      venue: "Dr. TP GANESAN AUDITORIUM - MINI HALL 1",
      mode: "Offline",
      participation_type: "TEAM",
      team_size: "2",
    },
    {
      id: 15,
      format: "TEAM EVENT",
      title: "EN VOGUE DEMAIN",
      open_to_all: false,
      date: "22.02.2026",
      reporting_time: "8.30 AM",
      venue: "Dr. TP GANESAN AUDITORIUM",
      mode: "Offline",
      participation_type: "TEAM",
      team_size: "12 to 15 members",
    },
  ],

  movies_and_dramatics: [
    {
      id: 16,
      format: "STAGE PLAY",
      title: "BROADWAY CHRONICLES",
      open_to_all: false,
      date: "21.02.2026",
      reporting_time: "8.30 AM",
      venue: "Dr. TP GANESAN AUDITORIUM",
      mode: "Offline",
      participation_type: "TEAM",
      team_size: "15 to 20 performers + 3 (accompanists)",
    },
    {
      id: 17,
      format: "STREET PLAY",
      title: "NUKKAD NATAK",
      open_to_all: false,
      date: "20.02.2026",
      reporting_time: "8.30 AM",
      venue: "VENDHAR SQUARE",
      mode: "Offline",
      participation_type: "TEAM",
      team_size: "15 to 20 performers",
    },
    {
      id: 18,
      format: "MONOLOGUE/MONOACT",
      title: "SOLO SAGA",
      open_to_all: true,
      date: "20.02.2026",
      reporting_time: "1.30 PM",
      venue: "TECH PARK 1 - JC BOSE HALL",
      mode: "Offline",
      participation_type: "SOLO",
      team_size: "1",
    },
    {
      id: 19,
      format: "SCRIPT WRITING",
      title: "INK & IMAGINATION",
      open_to_all: true,
      date: "22.02.2026",
      reporting_time: "8.00 AM",
      venue: "BIOTECH BLOCK - PROF. G N RAMACHANDRAN HALL",
      mode: "Offline",
      participation_type: "SOLO",
      team_size: "1",
    },
    {
      id: 20,
      format: "SHORT FILM",
      title: "CINEFEST",
      open_to_all: false,
      date: "22.02.2026",
      reporting_time: "11.30 AM",
      venue: "BIOTECH BLOCK - PROF. G N RAMACHANDRAN HALL",
      mode: "Offline",
      participation_type: "TEAM",
      team_size: "1 to 5 performers",
    },
    {
      id: 21,
      format: "NON-VERBAL STORYTELLING",
      title: "MIME",
      open_to_all: false,
      date: "21.02.2026",
      reporting_time: "1.30 PM",
      venue: "Dr. TP GANESAN AUDITORIUM - MINI HALL 1",
      mode: "Offline",
      participation_type: "TEAM",
      team_size: "10 MAX",
    },
    {
      id: 22,
      format: "ADZAP",
      title: "ADZAP",
      open_to_all: false,
      date: "21.02.2026",
      reporting_time: "8.30 AM",
      venue: "BIOTECH BLOCK - PROF. G. N. RAMACHANDRAN HALL",
      mode: "Offline",
      participation_type: "TEAM",
      team_size: "3 to 6 performers",
    },
  ],

  literary: [
    {
      id: 23,
      format: "IMPROV DEBATE",
      title: "SHIPWRECK",
      open_to_all: false,
      date: "20.02.2026",
      reporting_time: "8.30 AM",
      venue: "TECH PARK 1 - TURING HALL",
      mode: "Offline",
      participation_type: "SOLO",
      team_size: "1",
    },
    {
      id: 24,
      format: "POETRY WRITING",
      title: "SLAM POETRY",
      open_to_all: true,
      date: "21.02.2026",
      reporting_time: "9.30 AM",
      venue: "TECH PARK 1 - JC BOSE HALL",
      mode: "Offline",
      participation_type: "SOLO",
      team_size: "1",
    },
    {
      id: 25,
      format: "DEBATE",
      title: "DEBATE",
      open_to_all: false,
      date: "21.02.2026",
      reporting_time: "1.30 PM",
      venue: "TECH PARK 1 - JC BOSE HALL",
      mode: "Offline",
      participation_type: "TEAM",
      team_size: "3 V 3",
    },
    {
      id: 26,
      format: "Just A Minute",
      title: "JAM",
      open_to_all: false,
      date: "20.02.2026",
      reporting_time: "1.30 PM",
      venue: "TECH PARK 1 - TURING HALL",
      mode: "Offline",
      participation_type: "SOLO",
      team_size: "1",
    },
  ],

  creative_arts: [
    {
      id: 27,
      format: "CHARACTER DESIGNING",
      title: "CHARACTER ROULETTE",
      open_to_all: true,
      date: "21.02.2026",
      reporting_time: "9.30 AM",
      venue: "ARCHITECTURE BLOCK - CLASSROOMS",
      mode: "Offline",
      participation_type: "SOLO",
      team_size: "1",
    },
    {
      id: 28,
      format: "SKETCHING",
      title: "SKETCH IT OUT",
      open_to_all: false,
      date: "21.02.2026",
      reporting_time: "12.30 PM",
      venue: "ARCHITECTURE BLOCK - CLASSROOMS",
      mode: "Offline",
      participation_type: "SOLO",
      team_size: "1",
    },
    {
      id: 29,
      format: "CRAFTS",
      title: "BEST OUT OF WASTE",
      open_to_all: false,
      date: "20.02.2026",
      reporting_time: "8.30 AM",
      venue: "ARCHITECTURE BLOCK - CLASSROOMS",
      mode: "Offline",
      participation_type: "SOLO",
      team_size: "1",
    },
    {
      id: 30,
      format: "GRAPHIC DESIGNING",
      title: "DESIGN.exe",
      open_to_all: true,
      date: "22.02.2026",
      reporting_time: "8.30 AM",
      venue: "TECH PARK - CLASSROOMS(401&402)",
      mode: "Offline",
      participation_type: "SOLO",
      team_size: "1",
    },
    {
      id: 31,
      format: "DRAWING",
      title: "METAMORPHIC ART",
      open_to_all: false,
      date: "20.02.2026",
      reporting_time: "1.30 PM",
      venue: "ARCHITECTURE BLOCK -CLASSROOMS",
      mode: "Offline",
      participation_type: "SOLO",
      team_size: "1",
    },
  ],

  quiz: [
    {
      id: 32,
      format: "QUIZ",
      title: "TRIVIA QUIZ",
      open_to_all: true,
      date: "20.02.2026",
      reporting_time: "8.30 AM",
      venue: "TECH PARK 1 - JC BOSE HALL",
      mode: "Offline",
      participation_type: "TEAM",
      team_size: "1 to 3 members",
    },
  ],

  gaming: [
    {
      id: 33,
      format: "MOBILE",
      title: "E-FOOTBALL",
      open_to_all: true,
      date: "21.02.2026",
      reporting_time: "9.30 AM",
      venue: "Dr. TP GANESAN AUDITORIUM - MINI HALL 2",
      mode: "Online",
      participation_type: "SOLO",
      team_size: "1",
    },
    {
      id: 34,
      format: "MOBILE",
      title: "BGMI",
      open_to_all: true,
      date: "22.02.2026",
      reporting_time: "9.30 AM",
      venue: "Dr. TP GANESAN AUDITORIUM - MINI HALL 2",
      mode: "Online",
      participation_type: "TEAM",
      team_size: "4V4",
    },
    {
      id: 35,
      format: "MOBILE/TABLET",
      title: "FREE FIRE",
      open_to_all: true,
      date: "22.02.2026",
      reporting_time: "1.30 PM",
      venue: "Dr. TP GANESAN AUDITORIUM - MINI HALL 2",
      mode: "Online",
      participation_type: "TEAM",
      team_size: "4V4",
    },
    {
      id: 36,
      format: "PC/LAPTOP",
      title: "VALORANT",
      open_to_all: false,
      date: "21.02.2026",
      reporting_time: "1.30 PM",
      venue: "Dr. TP GANESAN AUDITORIUM - MINI HALL 2",
      mode: "Online",
      participation_type: "TEAM",
      team_size: "5V5",
    },
    {
      id: 37,
      format: "MOBILE",
      title: "CLASH ROYALE",
      open_to_all: false,
      date: "20.02.2026",
      reporting_time: "9.30 AM",
      venue: "Dr. TP GANESAN AUDITORIUM - MINI HALL 2",
      mode: "Online",
      participation_type: "SOLO",
      team_size: "1",
    },
  ],

  self_defence: [
    {
      id: 38,
      format: "BOXING",
      title: "THE MILAN BOXING ARENA",
      open_to_all: true,
      date: "20.02.2026",
      reporting_time: "9.30 AM",
      venue: "SPORTS COMPLEX",
      mode: "Offline",
      participation_type: "SOLO",
      team_size: "1",
    },
    {
      id: 39,
      format: "KICK-BOXING",
      title: "THE KICKFURY ARENA",
      open_to_all: true,
      date: "20.02.2026",
      reporting_time: "1.30 PM",
      venue: "SPORTS COMPLEX",
      mode: "Offline",
      participation_type: "SOLO",
      team_size: "1",
    },
  ],

  astrophilia: [
    {
      id: 40,
      format: "HACKATHON",
      title: "HACK THE STARS",
      open_to_all: true,
      date: "21.02.2026",
      reporting_time: "12.30 PM",
      venue: "TECH PARK 1 - CLASSROOMS (501&502)",
      mode: "Offline",
      participation_type: "TEAM",
      team_size: "2 to 4 members",
    },
    {
      id: 41,
      format: "CASE STUDY",
      title: "SPACE ODYSSEY",
      open_to_all: true,
      date: "20.02.2026",
      reporting_time: "8.30 AM",
      venue: "TECH PARK 1 - CLASSROOMS(401&402)",
      mode: "Offline",
      participation_type: "SOLO",
      team_size: "1",
    },
  ],
};
