// app/events/eventData.ts

export const rawEventData = {
  music: [
    {
      id: 1,
      format: "BANDS ( EASTERN )",
      title: "EASTERN UNBOUND",
      is_srm_only: false,
      date: "20-02-2026",
      reporting_time: "8:30 AM",
      venue: "TP GANESAN AUDITORIUM",
      mode: "Offline",
      participation_type: "TEAM",
      team_size: "8 to 10 members",
    },
    {
      id: 2,
      format: "BANDS ( WESTERN )",
      title: "WESTERN UNBOUND",
      is_srm_only: false,
      date: "21-02-2026",
      reporting_time: "8:30 AM",
      venue: "VENDHAR SQUARE",
      mode: "Offline",
      participation_type: "TEAM",
      team_size: "8 to 10 members",
    },
    {
      id: 3,
      format: "RAP",
      title: "VERSE CLASH",
      is_srm_only: false,
      date: "21-02-2026",
      reporting_time: "2:30 PM",
      venue: "VENDHAR SQUARE",
      mode: "Offline",
      participation_type: "SOLO",
      team_size: "1",
    },
    {
      id: 4,
      format: "BEATBOX",
      title: "RHYTHM RUMBLE",
      is_srm_only: false,
      date: "21-02-2026",
      reporting_time: "2:30 PM",
      venue: "VENDHAR SQUARE",
      mode: "Offline",
      participation_type: "SOLO",
      team_size: "1",
    },
    {
      id: 5,
      format: "INSTRUMENTAL",
      title: "CRESCENDO",
      is_srm_only: false,
      date: "20-02-2026",
      reporting_time: "1:30 PM",
      venue: "TP GANESAN AUDITORIUM - MINI HALL 1",
      mode: "Offline",
      participation_type: "SOLO",
      team_size: "1",
    },
    {
      id: 6,
      format: "WESTERN VOCAL",
      title: "ECHOVERSE",
      is_srm_only: false,
      date: "21-02-2026",
      reporting_time: "1:30 PM",
      venue: "BIOTECH BLOCK - PROF. G. N. RAMACHANDRAN HALL",
      mode: "Offline",
      participation_type: "SOLO",
      team_size: "1",
    },
    {
      id: 7,
      format: "EASTERN CLASSICAL VOCAL",
      title: "SWARANJALI",
      is_srm_only: false,
      date: "20-02-2026",
      reporting_time: "1:30 PM",
      venue: "BIOTECH BLOCK - PROF. G. N. RAMACHANDRAN HALL",
      mode: "Offline",
      participation_type: "SOLO",
      team_size: "1",
    },
  ],

  dance: [
    {
      id: 8,
      format: "CLASSICAL",
      title: "RASADHARA",
      is_srm_only: false,
      date: "21-02-2026",
      reporting_time: "8:30 AM",
      venue: "TP GANESAN AUDITORIUM - MINI HALL 1",
      mode: "Offline",
      participation_type: "SOLO",
      team_size: "1",
    },
    {
      id: 9,
      format: "CREATIVE CHOREOGRAPHY",
      title: "NRITYA NATYA",
      is_srm_only: false,
      date: "20-02-2026",
      reporting_time: "1:30 PM",
      venue: "TP GANESAN AUDITORIUM",
      mode: "Offline",
      participation_type: "TEAM",
      team_size: "8 to 20 performers",
    },
    {
      id: 10,
      format: "WESTERN",
      title: "METROPOLIS MOVES",
      is_srm_only: false,
      date: "20-02-2026",
      reporting_time: "8:30 AM",
      venue: "TP GANESAN AUDITORIUM - MINI HALL 1",
      mode: "Offline",
      participation_type: "SOLO",
      team_size: "1",
    },
    {
      id: 11,
      format: "1 vs 1 BATTLE",
      title: "URBAN SHOWDOWN",
      is_srm_only: false,
      date: "20-02-2026",
      reporting_time: "1:30 PM",
      venue: "VENDHAR SQUARE",
      mode: "Offline",
      participation_type: "SOLO",
      team_size: "1",
    },
    {
      id: 12,
      format: "GROUP DANCE",
      title: "CHOREONITE",
      is_srm_only: false,
      date: "21-02-2026",
      reporting_time: "1:30 PM",
      venue: "TP GANESAN AUDITORIUM",
      mode: "Offline",
      participation_type: "TEAM",
      team_size: "8 to 25 performers",
    },
    {
      id: 13,
      format: "TRADITIONAL FOLK",
      title: "VIRSA",
      is_srm_only: false,
      date: "22-02-2026",
      reporting_time: "8:30 AM",
      venue: "VENDHAR SQUARE",
      mode: "Offline",
      participation_type: "TEAM",
      team_size: "8 to 20 performers",
    },
  ],

  fashion: [
    {
      id: 14,
      format: "DUO EVENT",
      title: "AU-DELÀ: Mr. & MISS MILAN",
      is_srm_only: false,
      date: "22-02-2026",
      reporting_time: "1:30 PM",
      venue: "TP GANESAN AUDITORIUM - MINI HALL 1",
      mode: "Offline",
      participation_type: "TEAM",
      team_size: "2",
    },
    {
      id: 15,
      format: "TEAM EVENT",
      title: "EN VOGUE DEMAIN",
      is_srm_only: false,
      date: "22-02-2026",
      reporting_time: "8:30 AM",
      venue: "TP GANESAN AUDITORIUM",
      mode: "Offline",
      participation_type: "TEAM",
      team_size: "12 to 15 members",
    },
  ],

  movies_and_dramatics: [
    {
      id: 16,
      format: "STAGE PLAY",
      title: "BROADWAY CHRONICLES",
      is_srm_only: false,
      date: "21-02-2026",
      reporting_time: "8:30 AM",
      venue: "TP GANESAN AUDITORIUM",
      mode: "Offline",
      participation_type: "TEAM",
      team_size: "15 to 20 + 3",
    },
    {
      id: 17,
      format: "STREET PLAY",
      title: "NUKKAD NATAK",
      is_srm_only: false,
      date: "20-02-2026",
      reporting_time: "8:30 AM",
      venue: "VENDHAR SQUARE",
      mode: "Offline",
      participation_type: "TEAM",
      team_size: "15 to 20 performers",
    },
    {
      id: 18,
      format: "ACTING",
      title: "SOLO SAGA",
      is_srm_only: false,
      date: "21-02-2026",
      reporting_time: "1:30 PM",
      venue: "TP GANESAN AUDITORIUM - MINI HALL 2",
      mode: "Offline",
      participation_type: "SOLO",
      team_size: "1",
    },
    {
      id: 21,
      format: "MIME",
      title: "MIME",
      is_srm_only: false,
      date: "21-02-2026",
      reporting_time: "1:30 PM",
      venue: "TP GANESAN AUDITORIUM - MINI HALL 1",
      mode: "Offline",
      participation_type: "TEAM",
      team_size: "8 to 10 members",
    },
  ],

  literary: [
    {
      id: 23,
      format: "SHIPWRECK",
      title: "SHIPWRECK",
      is_srm_only: false,
      date: "20-02-2026",
      reporting_time: "8:30 AM",
      venue: "BIOTECH BLOCK - PROF. G. N. RAMACHANDRAN HALL",
      mode: "Offline",
      participation_type: "SOLO",
      team_size: "1",
    },
    {
      id: 25,
      format: "DEBATE",
      title: "DEBATE",
      is_srm_only: false,
      date: "21-02-2026",
      reporting_time: "8:30 AM",
      venue: "ARCHITECTURE BLOCK - AUDITORIUM",
      mode: "Offline",
      participation_type: "TEAM",
      team_size: "2",
    },
    {
      id: 26,
      format: "JUST A MINUTE",
      title: "JAM",
      is_srm_only: false,
      date: "20-02-2026",
      reporting_time: "8:30 AM",
      venue: "ARCHITECTURE BLOCK - AUDITORIUM",
      mode: "Offline",
      participation_type: "SOLO",
      team_size: "1",
    },
  ],

  gaming: [
    {
      id: 33,
      format: "MOBILE",
      title: "E-FOOTBALL",
      is_srm_only: false,
      date: "21-02-2026",
      reporting_time: "9:30 AM",
      venue: "TP GANESAN AUDITORIUM - MINI HALL 2",
      mode: "Online",
      participation_type: "SOLO",
      team_size: "1",
    },
    {
      id: 34,
      format: "MOBILE",
      title: "BGMI",
      is_srm_only: false,
      date: "22-02-2026",
      reporting_time: "9:30 AM",
      venue: "TP GANESAN AUDITORIUM - MINI HALL 2",
      mode: "Online",
      participation_type: "TEAM",
      team_size: "4V4",
    },
    {
      id: 36,
      format: "PC",
      title: "VALORANT",
      is_srm_only: false,
      date: "20-02-2026",
      reporting_time: "9:30 AM",
      venue: "ONLINE",
      mode: "Online",
      participation_type: "TEAM",
      team_size: "5V5",
    },
  ],

  self_defence: [
    {
      id: 38,
      format: "BOXING",
      title: "THE MILAN BOXING ARENA",
      is_srm_only: false,
      date: "20-02-2026",
      reporting_time: "9:30 AM",
      venue: "SPORTS COMPLEX",
      mode: "Offline",
      participation_type: "SOLO",
      team_size: "1",
    },
    {
      id: 39,
      format: "KICK-BOXING",
      title: "THE KICKFURY ARENA",
      is_srm_only: false,
      date: "20-02-2026",
      reporting_time: "1:30 PM",
      venue: "SPORTS COMPLEX",
      mode: "Offline",
      participation_type: "SOLO",
      team_size: "1",
    },
  ],

  astrophilia: [
    {
      id: 40,
      format: "HACKATHON",
      title: "HACK THE STARS",
      is_srm_only: false,
      date: "21-02-2026",
      reporting_time: "12:30 PM",
      venue: "TECH PARK 1 - CLASSROOMS (501&502)",
      mode: "Offline",
      participation_type: "TEAM",
      team_size: "2 to 4 members",
    },
    {
      id: 41,
      format: "CASE STUDY",
      title: "SPACE ODYSSEY",
      is_srm_only: false,
      date: "20-02-2026",
      reporting_time: "8:30 AM",
      venue: "TECH PARK 1 - CLASSROOMS(401&402)",
      mode: "Offline",
      participation_type: "SOLO",
      team_size: "1",
    },
  ],
};
